# docker-compose.yml

version: '3.8'

services:
  backend:
    env_file:
      - .env
    build: .
    networks:
      - db_network
      - api_connection
    links:
      - db:database
    ports:
      - 8000:8000
      - 80:80
    depends_on:
      - db
    environment:
      - POSTGRES_USER=$${DB_USER}
      - POSTGRES_DB=$${DB_NAME}
      - POSTGRES_PASSWORD=$${DB_PASSWORD}
    restart: on-failure

  db:
    env_file:
      - .env
    networks:
      - db_network
    build: postgres_db/.
    ports:
    - 5437:5432
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_DB=${DB_NAME}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_HOST_AUTH_METHOD=trust
#    volumes:
#      - postgres_data:/var/lib/postgresql/data/
  frontend:
    build: ../coolUrbanSpaces/.
    ports:
      - 5000:80
    networks:
      - api_connection

volumes:
  postgres_data:

networks:
  db_network:
    driver: bridge
  api_connection:
    driver: bridge
