# docker-compose.yml

version: '3.8'

services:
  web:
    env_file:
      - .env
    command: bash -c 'while [ !</dev/tcp/db/5432 ] && [ `ping -c 1 factory` ]; do sleep 1; done; sleep 5; uvicorn cool_urban_spaces_backend.main:app --host 0.0.0.0'
    build: .
    networks:
      - db_network
    links:
      - db:database
    ports:
      - 8000:8000
      - 80:80
    depends_on:
      - db
      - factory
    environment:
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_DB=${DB_NAME}
    restart: on-failure
    volumes:
      - ./static/:/srv/static

  db:
    networks:
      - db_network
    env_file:
      - .env
    build: postgres_db/.
    ports:
    - 5437:5432
    environment:
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_DB=${DB_NAME}
    volumes:
      - postgres_data:/var/lib/postgresql/data/
  factory:
    networks:
      - db_network
    build: frontend_factory/.
    volumes:
    - ./static/:/home/developer/coolUrbanSpaces/build/web/

volumes:
  postgres_data:

networks:
  db_network:
    driver: bridge
